config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "tweets#index"

  # Tweets
  get 'tweets/drafts', to: 'tweets#drafts'
  get 'tweets/attachments/:filename', to: 'tweets#attachments', as: 'tweet_attachments'
  post 'tweets/:id/publish', to: 'tweets#publish', as: 'publish_tweet'
  post 'tweets/:id/like', to: 'tweets#like', as: 'like_tweet'
  resources :tweets do
    post 'comments/:id/like', to: 'comments#like', as: 'like_comment'
    resources :comments
  end

  # Users & Login
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/abstract_like.rb
class AbstractLike < ApplicationRecord
  belongs_to :user
  belongs_to :abstract_tweet, dependent: :destroy

  trigger.after(:insert) do
    "UPDATE abstract_tweets SET likes_count = likes_count + 1 WHERE id = NEW.abstract_tweet_id"
  end

  trigger.after(:delete) do
    "UPDATE abstract_tweets SET likes_count = likes_count - 1 WHERE id = OLD.abstract_tweet_id"
  end
end

app/models/abstract_tweet.rb
class AbstractTweet < ApplicationRecord
    belongs_to :user
    enum status: { published: 0, drafted: 1, deleted: 2 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
require_relative 'abstract_tweet'

class Comment < AbstractTweet
  belongs_to :tweet

  trigger.after(:insert) do
    "UPDATE abstract_tweets SET comments_count = comments_count + 1 WHERE id = NEW.tweet_id"
  end

  trigger.after(:delete) do
    "UPDATE abstract_tweets SET comments_count = comments_count - 1 WHERE id = OLD.tweet_id"
  end
end

app/models/tweet.rb
require_relative 'abstract_tweet'

class Tweet < AbstractTweet
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/login' unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_if_editable, only: [:update, :destroy]

  def index
    @tweet = Tweet.find(params[:tweet_id])
    @comments = Comment.where(tweet: @tweet).order(created_at: :desc).eager_load(:tweet, :user).all
  end

  def new
    @tweet = Tweet.find(params[:tweet_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.tweet_id = params[:tweet_id]
    @comment.save
  end

  def edit
    @tweet = Tweet.find(params[:tweet_id])
    @comment = Comment.find(params[:id])
  end

  def update
    if @comment.update(comment_params)
      redirect_to tweet_comments_url
    else
      render :edit
    end
  end

  def destroy
    @comment.delete
    redirect_to tweet_comments_url
  end

  def like
    @comment = Comment.find(params[:id])
    AbstractLike.create(abstract_tweet: @comment, user: current_user)
    redirect_back(fallback_location: root_path)
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def check_if_editable
      @comment = Comment.find(params[:id])
      redirect_back(fallback_location: root_path) unless current_user == @comment.user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
     @user = User.find_by(username: params[:username])
     if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path
     else
        redirect_to '/login'
     end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :check_if_editable, only: [:update, :publish, :destroy]

  def index
    @tweets = Tweet.where(status: :published).order(created_at: :desc).eager_load(:user).all
  end

  def drafts
    @draft_tweets = Tweet.where(status: :drafted, user: current_user).order(created_at: :desc).all
  end

  def attachments
    filename = "#{params[:filename]}.#{params[:format]}"
    send_file(Rails.root.join("storage", filename), filename: filename, type: "mime/type")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    @tweet.status = :drafted if params[:commit] == 'Draft Tweet'
    attachments_paths = upload_files(params[:tweet][:attachments])
    @tweet.attachments = attachments_paths.join(',')
    @tweet.save
    redirect_to tweets_path
  end

  def show
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    attachments_paths = upload_files(params[:tweet][:attachments])
    @tweet.attachments = attachments_paths.join(',')
    if @tweet.update(tweet_params)
      redirect_to tweets_drafts_url
    else
      render :edit
    end
  end

  def publish
    @tweet.status = :published
    @tweet.save()
    redirect_to tweets_path
  end

  def like
    @tweet = Tweet.find(params[:id])
    AbstractLike.create(abstract_tweet: @tweet, user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @tweet.status = :deleted
    @tweet.save()
    redirect_to tweets_drafts_url
  end

  private

    def tweet_params
      params.require(:tweet).permit(:content)
    end

    def upload_files(files)
      attachments_paths = []
      (files or []).map do |file|
        extension = file.original_filename.split('.')[-1]
        filename = "#{generate_random_filename}.#{extension}"
        File.binwrite(Rails.root.join("storage", filename), file.read)
        filename
      end
    end

    def generate_random_filename
      return SecureRandom.urlsafe_base64
    end

    def check_if_editable
      @tweet = Tweet.find(params[:id])
      redirect_back(fallback_location: root_path) unless current_user == @tweet.user and @tweet.status == 'drafted'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password))
    redirect_to '/login'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
  By <%= comment.user.username %> on
  <%= comment.created_at.strftime('%c') %>
  <p><%= comment.content %></p>
  <%= button_to 'Like', tweet_like_comment_path(comment.tweet, comment) %>
  <p><%= "Likes (#{comment.likes_count})" %></p>
  <% if @current_user == comment.user %>
    <%= button_to "Edit", edit_tweet_comment_path(comment.tweet, comment), method: :get%><br/>
    <%= button_to "Delete", tweet_comment_path(comment.tweet, comment), method: :delete%><br/>
  <% end %>
</li>

app/views/comments/_new.html.erb
<h4>New Comment</h4>
<%= form_for Comment.new, url: tweet_comments_path, remote: true do |f|%>
  <%= f.label :Comment%><br>
  <%= f.text_field :content, class: 'comment'%><br>
  <%= f.submit %>
<%end%>

app/views/comments/_tweet.html.erb
<h3>Tweet</h3>
<p>
  By <b><%= @tweet.user.username %></b> on
  <%= @tweet.created_at.strftime('%c') %>
  <p><%= @tweet.content %></p>
  <p>
    <% (@tweet.attachments or '').split( ',').each_with_index do |attachment, index| %>
      <%= link_to "Attachment #{index + 1}", tweet_attachments_url(attachment) %>
    <% end %>
  </p>
  <%= button_to 'Like', like_tweet_path(@tweet) %>
  <p>
    <%= "Likes (#{@tweet.likes_count})" %>
    <%= "Comments (#{@tweet.comments_count})" %>
  </p>
</p>

app/views/comments/create.js.erb
$('#comments_panel').append("<%= j render @comment %>");

$('.comment').val('');

app/views/comments/edit.html.erb
<%= render "tweet" %>
<h1>Edit Comment</h1>
<%= form_for @comment, url: tweet_comment_path do |f|%>
  <%= f.label :Comment%><br>
  <%= f.text_field :content%><br>
  <%= f.submit %>
<%end%>

app/views/comments/index.html.erb
<%= render "tweet" %>
<h4>Comments</h4>
<ul>
  <div id='comments_panel'>
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  </div>
</ul>
<%= render partial: 'comments/new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blackboardradio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <h1>Hello <%= current_user.username %> !</h1>
      <%= button_to "Logout", '/logout', method: :delete%>
      <p>
        <%= link_to 'Home', root_path %><br/>
        <%= link_to 'Add Tweet', new_tweet_url %><br/>
        <%= link_to 'Drafted Tweet', tweets_drafts_url %><br/>
      </p>
    <%end%>

    <%= yield %>
  </body>
</html>

app/views/tweets/drafts.html.erb
<h1>Draft Tweets</h1>
<ul>
  <% @draft_tweets.each do |tweet| %>
    <li>
      <p><%= tweet.content %></p>
      <p>
        <% (tweet.attachments or '').split( ',').each_with_index do |attachment, index| %>
          <%= link_to "Attachment #{index + 1}", tweet_attachments_url(attachment) %>
        <% end %>
      </p>
      <%= button_to "Publish", publish_tweet_path(tweet)%>
      <%= button_to "Edit", edit_tweet_path(tweet), method: :get%>
      <%= button_to "Delete", tweet_path(tweet), method: :delete%>
    </li>
  <% end %>
</ul>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>
<%= form_for @tweet do |f|%>
  <%= f.label :Tweet%><br>
  <%= f.text_field :content%><br>
  <%= f.file_field :attachments, multiple: true%><br>
  <%= f.submit %>
<%end%>

app/views/tweets/index.html.erb
<h1>Tweets Feed</h1>
<ul>
  <% @tweets.each do |tweet| %>
    <li>
      By <b><%= tweet.user.username %></b> on
      <%= tweet.created_at.strftime('%c') %>
      <p><%= tweet.content %></p>
      <p>
        <% (tweet.attachments or '').split( ',').each_with_index do |attachment, index| %>
          <%= link_to "Attachment #{index + 1}", tweet_attachments_url(attachment) %>
        <% end %>
      </p>
      <%= button_to 'Like', like_tweet_path(tweet) %>
      <p>
        <%= "Likes (#{tweet.likes_count})" %>
        <%= link_to "Comments (#{tweet.comments_count})", tweet_comments_path(tweet) %>
      </p>
    </li>
    <br/>
  <% end %>
</ul>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>
<%= form_for @tweet do |f|%>
  <%= f.label :Tweet%><br>
  <%= f.text_field :content%><br>
  <%= f.file_field :attachments, multiple: true%><br>
  <%= f.submit name: :commit, value: 'Publish Tweet' %>
  <%= f.submit name: :commit, value: 'Draft Tweet' %>
<%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>